#!/bin/sh

lb clean noauto "$@"

rm -fv config/binary \
	config/bootstrap \
	config/chroot \
	config/common \
	config/source \
	config/package-lists/live.list.chroot

if [ -e config/hooks/ ]; then
	find config/hooks/ -type l \
		| xargs --no-run-if-empty rm -f
fi
